version: "3.9"

services:
  api:
    build: .
    env_file: .env
    volumes: [".:/app"]
    ports: ["8000:8000"]
    depends_on: [db, redis]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: invest
      POSTGRES_DB: investdb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  worker:
    build: .
    command: celery -A backend.app.services.tasks.ingest.celery_app worker -l INFO
    env_file: .env
    volumes: [".:/app"]
    depends_on: [api, redis, db]

  beat:
    build: .
    command: celery -A backend.app.services.tasks.ingest.celery_app beat -l INFO
    env_file: .env
    volumes: [".:/app"]
    depends_on: [worker, redis]

volumes:
  pgdata:

